baseurl = "https://kseniya.io/"
title = "Kseniya"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Kseniya Lifanova"
    description = "Kseniya Lifanova's personal website"
    keywords = "blog,developer,personal"
    info = "Co-founder, Smart Contract Developer, Ethereum ❤️"
    avatarurl = "images/photo.png"
    footercontent = "this is me"

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false

    rtl = false

    # Use inverted colors
    inverted = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = ["css/custom.css"]

[taxonomies]
  series = "series"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/kseniya292/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/devgirlla/"
[[params.social]]
    name = "Instagram"
    icon = "fab fa-instagram"
    weight = 3
    url = "https://instagram.com/devgirlla/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/kseniya-lifanova-aa50b19/"
[[params.social]]
    name = "Medium"
    icon = "fab fa-medium"
    weight = 5
    url = "https://medium.com/@kseniya292"

# Menu links
[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
[[menu.main]]
    name = "Speaking"
    weight = 3
    url  = "/speaking/"
[[menu.main]]
    name = "Contact"
    weight = 4
    url  = "/contact/"